name: Release Please with Docker Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Release-Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.PAT }}

  docker:
    if: github.ref == 'refs/heads/main'
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Version from Release-Please Manifest
        id: get_version
        run: |
          VERSION=$(jq -r '."."' < .release-please-manifest.json)
          echo "version=$VERSION" >> $GITHUB_ENV
     
      - name: Debug release-please output
        run: echo "Release version ${{ steps.release.outputs.version }}"


      - name: Build Docker Image
        env:
          VERSION: ${{ steps.release.outputs.version }}  # Assuming this pulls the version from Release-Please
        run: |
          docker build -t soubarniya/go-api:$VERSION .
          

      - name: Push Docker Image
        env:
          VERSION: ${{ steps.release.outputs.version }}
        run: |
          docker push soubarniya/go-api:$VERSION
          

